apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: teams-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - cluster: engineering
            url: https://kubernetes.default.svc
          - cluster: staging
            url: https://staging.example.com
  template:
    metadata:
      name: '{{cluster}}-guestbook'
      labels:
        app.kubernetes.io/name: guestbook
    spec:
      project: platform
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: v1.4.0
        path: guestbook
      destination:
        server: '{{url}}'
        namespace: guestbook
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
