repos:
  - repo: local
    hooks:
      - id: argocd-lint
        name: argocd-lint
        entry: argocd-lint manifests --rules argocd-lint-config/baseline.yaml --severity-threshold=warn
        language: system
        pass_filenames: false
