apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: open
  namespace: argocd
spec:
  description: Project without restrictions to illustrate new guardrails
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
