apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-helm
  namespace: argocd
  labels:
    app.kubernetes.io/name: guestbook-helm
spec:
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.0.0
    chart: nginx
    helm:
      values: |
        replicaCount: 2
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
