apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argocd-lint-
spec:
  entrypoint: lint
  arguments:
    parameters:
      - name: repo
        value: https://github.com/harchuk/argocd-lint-example.git
      - name: revision
        value: main
  templates:
    - name: lint
      steps:
        - - name: baseline
            template: lint-baseline
        - - name: security
            template: lint-security

    - name: lint-baseline
      inputs:
        artifacts:
          - name: repo
            path: /workspace
            git:
              repo: '{{workflow.parameters.repo}}'
              revision: '{{workflow.parameters.revision}}'
      container:
        image: ghcr.io/harchuk/argocd-lint/argocd-lint:latest
        command:
          - argocd-lint
        args:
          - manifests
          - --rules
          - argocd-lint-config/baseline.yaml
          - --severity-threshold
          - warn
        workingDir: /workspace

    - name: lint-security
      inputs:
        artifacts:
          - name: repo
            path: /workspace
            git:
              repo: '{{workflow.parameters.repo}}'
              revision: '{{workflow.parameters.revision}}'
      container:
        image: ghcr.io/harchuk/argocd-lint/argocd-lint:latest
        command:
          - argocd-lint
        args:
          - manifests
          - --rules
          - argocd-lint-config/security.yaml
          - --plugin-dir
          - policy-plugins/custom
          - --format
          - json
        workingDir: /workspace
