# Reusable GitHub Actions job that runs argocd-lint from the published container image.
# Demonstrates how to parameterize severity threshold and optional rendering tools.
name: lint-argocd

on:
  workflow_call:
    inputs:
      severity-threshold:
        required: false
        default: warn
        type: string
      render:
        required: false
        default: false
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare tooling (optional render)
        if: inputs.render == true
        run: |
          set -euo pipefail
          mkdir -p .lint-tools
          curl -sSL https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz -o .lint-tools/helm.tgz
          tar -xzf .lint-tools/helm.tgz -C .lint-tools linux-amd64/helm
          mv .lint-tools/linux-amd64/helm .lint-tools/helm
          rm -rf .lint-tools/linux-amd64 .lint-tools/helm.tgz
          curl -sSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.1.0/kustomize_v5.1.0_linux_amd64.tar.gz -o .lint-tools/kustomize.tgz
          tar -xzf .lint-tools/kustomize.tgz -C .lint-tools kustomize
          rm .lint-tools/kustomize.tgz
          chmod +x .lint-tools/helm .lint-tools/kustomize

      - name: Run argocd-lint
        env:
          SEVERITY_THRESHOLD: ${{ inputs.severity-threshold }}
          WITH_RENDER: ${{ inputs.render }}
        run: |
          set -euo pipefail
          ARGS=(manifests --rules argocd-lint-config/baseline.yaml --severity-threshold "${SEVERITY_THRESHOLD}")
          if [[ "${WITH_RENDER}" == "true" ]]; then
            ARGS+=(--render --helm-binary /workspace/.lint-tools/helm --kustomize-binary /workspace/.lint-tools/kustomize)
          fi
          docker run --rm \
            -v "$PWD:/workspace" \
            -w /workspace \
            ghcr.io/harchuk/argocd-lint/argocd-lint:latest \
            "${ARGS[@]}"
