stages:
  - lint

variables:
  GOPATH: "$CI_PROJECT_DIR/.go"
  GOCACHE: "$CI_PROJECT_DIR/.cache/go-build"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .go
    - .cache/go-build

lint:argocd:
  image: golang:1.22
  stage: lint
  script:
    - go env -w GOPATH=$GOPATH GOCACHE=$GOCACHE
    - go install github.com/argocd-lint/argocd-lint/cmd/argocd-lint@latest
    - $GOPATH/bin/argocd-lint manifests --rules argocd-lint-config/baseline.yaml --severity-threshold=warn
    - $GOPATH/bin/argocd-lint manifests --rules argocd-lint-config/prod-strict.yaml --format json > argocd-lint.json
  artifacts:
    when: always
    paths:
      - argocd-lint.json
