stages:
  - lint

image: docker:24.0.5

services:
  - name: docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

lint:argocd:
  stage: lint
  before_script:
    - apk add --no-cache curl tar
  script:
    - docker pull ghcr.io/harchuk/argocd-lint/argocd-lint:latest
    - docker run --rm -v "$CI_PROJECT_DIR:/workspace" -w /workspace ghcr.io/harchuk/argocd-lint/argocd-lint:latest argocd-lint manifests --rules argocd-lint-config/baseline.yaml --severity-threshold=warn
    - docker run --rm -v "$CI_PROJECT_DIR:/workspace" -w /workspace ghcr.io/harchuk/argocd-lint/argocd-lint:latest argocd-lint manifests --rules argocd-lint-config/prod-strict.yaml --format json > argocd-lint.json
  artifacts:
    when: always
    paths:
      - argocd-lint.json
