apiVersion: v1
kind: Service
metadata:
  name: payments-api
  labels:
    app: payments-api
spec:
  type: ClusterIP
  selector:
    app: payments-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
