apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/repo.git
    targetRevision: HEAD
    path: applications/platform
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
