apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
patchesStrategicMerge:
  - patch-replicas.yaml
configMapGenerator:
  - name: payments-api-config
    literals:
      - LOG_LEVEL=info
